Repository LTCatt/PCL2Help, pull requests merged in 2021-04, with the labels that each got.

#7 完善了提交帮助的帮助
  帮助/提交帮助.xaml
Labels: 新页面提议

#12 添加帮助和常用网站
  个性化/备份PCL的设置.json
  个性化/备份PCL的设置.xaml
  网站/MCMOD.json
Labels: 处理中, 新页面提议

#10 完善README.md、完善 “个性化 → XAML 格式”和添加一个帮助
  README.md
  个性化/XAML 格式.json
  个性化/XAML 格式.xaml
  个性化/登录方式.json
  个性化/登录方式.xaml
Labels: 处理中, 新页面提议

#25 优化了README.md
  README.md
Labels: 优化建议, 已处理

#19 创建编写规范，创建Git提交帮助条目，修改一些条目
  个性化/XAML 格式.json
  个性化/XAML 格式.xaml
  帮助/提交帮助 - Git.json
  帮助/提交帮助 - Git.xaml
  帮助/提交帮助 - GitHub Desktop.json
  帮助/提交帮助 - GitHub Desktop.xaml
  帮助/提交帮助 - VSCode.json
  帮助/提交帮助 - VSCode.xaml
  帮助/提交帮助.xaml
  帮助/编写规范.json
  帮助/编写规范.xaml
  帮助/自定义帮助.xaml
Labels: 处理中, 新页面提议

#28 优化了 提交帮助 - GitHub Desktop.xaml
  帮助/提交帮助 - GitHub Desktop.xaml
Labels: 优化建议, 处理中

#33 添加 DynamicResource 相关条目，重画了个 README 顶图，备份注册表脚本
  README.md
  个性化/XAML 格式.json
  个性化/XAML 格式.xaml
  启动器/备份设置.json
  启动器/备份设置.xaml
  帮助/提交帮助 - VSCode.json
  帮助/提交帮助 - VSCode.xaml
  网站/Mineplugin Wiki.json
Labels: 优化建议, 处理中

#30 增加 "材质包安装" 帮助
  个性化/材质包安装.json
  个性化/材质包安装.xaml
Labels: 处理中, 新页面提议
