Repository LTCatt/PCL2Help, pull requests merged in 2021-07, with the labels that each got.

#50 帮助库的新增与完善：皮肤导出与内存调整的修订
  Minecraft/设置分配内存大小.json
  Minecraft/设置分配内存大小.xaml
  启动器/如何导出角色的皮肤.json
  启动器/如何导出角色的皮肤.xaml
Labels: 优化建议, 新页面提议

#53 优化 "材质包安装” 教程 图片加载
  Minecraft/资源包安装.xaml
Labels: 优化建议

#52 增加一部分教程
  Minecraft/CurseForge 整合包安装.json
  Minecraft/CurseForge 整合包安装.xaml
  Minecraft/存档导入.json
  Minecraft/存档导入.xaml
  Minecraft/安装 Mod.json
  Minecraft/安装 Mod.xaml
Labels: 新页面提议

#61 在“安装光影”补充 Iris Shaders 相关内容
  Minecraft/在 Minecraft 中使用光影.xaml
  Minecraft/安装光影.json
  Minecraft/安装光影.xaml
Labels: 优化建议
